export const ActionTypes={
    FETCH_PRODUCTS:"FETCH_PRODUCTS",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    // REMOVE_PRODUCT:"REMOVE_PRODUCT",
    ADD_TO_CART:"ADD_TO_CART",
    DELETE_TO_CART:"DELETE_TO_CART",
    DELETE_SINGLE_VALUE:"DELETE_SINGLE_VALUE",
    CLEAR_CART:"CLEAR_CART"
   

}